### ISSUE TITLE
Add Support for SSL/TLS Client Certificates

### ISSUE THREAD

**Issue by Verequies** [khlieng/dispatch#1]
Great job you're doing with dispatch. Wondering if you could add support for client certificates? I'm currently running a server that requires such support and I'd like to use a web client to connect to it. Would be great to see such support as no other web clients currently support this feature.

**Comment by khlieng** [comment]
Yeah this will be added pretty soon.

**Comment by khlieng** [comment]
I have added support for uploading client certificates through settings now.

**Comment by Verequies** [comment]
Okay sweet, where the cert does it upload to? Local cache or the actual server? Just wondering cause if it was uploading to the actual server it defeats the purpose of a client cert does it not? Also you may want to add the option for .pem files. Which are just the Cert + Key combined into one.

**Comment by khlieng** [comment]
Its stored at the dispatch server, where its used for making IRC connections.

Custom ports can be set by entering server:port into the address field, I plan to split that field eventually.

**Comment by Verequies** [comment]
Having trouble setting up my own environment to test this, followed the provided instructions but I keep getting 'bash: dispatch: command not found'. Also I'm still unable to make a connection to my server using your hosted version, just a blank white screen.

**Comment by khlieng** [comment]
Go puts compiled programs in $GOPATH/bin, do have that in your PATH? https://golang.org/doc/code.html#GOPATH

**Comment by Verequies** [comment]
Okay got it working, thanks, completely overlooked the '/bin' in the documentation. Dispatch seems to be ignoring the config.toml. I've enabled HTTPS, and am using a local cert/key, however Dispatch keeps listening on only port 80. Even if I change port 80, it Dispatch listens on port 80. Also where abouts is the config that allows you to set the default values for the fields?

**Comment by khlieng** [comment]
And thats the same config as the one that gets opened when running dispatch config?

**Comment by Verequies** [comment]
Yeah, both the '~/.go/src/github.com/khlieng/dispatch/config.toml' & '~/.dispatch/config.toml' are the same.

**Comment by khlieng** [comment]
So the one at go/src/github.com/khlieng/dispatch/ is just the defaults that get embedded into the binary, the other one at wherever dispatch is storing the rest of its data should be working.

**Comment by Verequies** [comment]
Ah, okay. Now that I've specified the Cert & Private Key, I get the following runtime errors (Check log).
[dispatch.txt](https://github.com/khlieng/dispatch/files/89720/dispatch.txt)

**Comment by khlieng** [comment]
It appears the Go standard library doesnt like your key: https://github.com/golang/go/issues/13699

**Comment by Verequies** [comment]
Generated a new key/cert, seems to work fine now. However I still can't make a connection to my IRC Server, just blank, no text. I uploaded my client cert (which gets verified by my servers CA), then I entered my servers details in and clicked connect. Also is it possible to set the default server settings so I don't have to keep entering them?

**Comment by khlieng** [comment]
Did the connection indicator turn green?

**Comment by Verequies** [comment]
In the address field when I specify 'verdum.tk:2045', Verdum (Server Name), doesn't even come up on the left side bar. However if I specify 'verdum.tk', the name does and the indicator is red.

**Comment by khlieng** [comment]
There was an issue with custom ports on the client that i just pushed a fix for.

**Comment by Verequies** [comment]
Seems to have fixed that issue, however I'm still getting nothing when I try to connect.

**Comment by khlieng** [comment]
Yeah sure.

**Comment by Verequies** [comment]
How can I contact you? My email is HamishClaxton@gmail.com.
